### ISSUE TITLE
最好遵循C#编码约定而不是Java的习惯, 文件读写和网络请求最好使用异步操作以避免阻塞

### ISSUE THREAD

**Issue by Cjjj-sys** [HeyCrab3/NewCrabSS#2]
https://docs.microsoft.com/zh-cn/dotnet/csharp/fundamentals/coding-style/coding-conventions
比如方法名应该为MethodName而不是methodName

使用File.ReadAllTextAsync而不是File.ReadAllText
使用httpClient.PostAsync

在连接多条字符串（包含变量时），最好使用字符串内插语法
```csharp
var fullName = $"{firstName} {lastName}";
```

**Comment by HeyCrab3** [comment]
好的，收到反馈，下个版本改

**Comment by HeyCrab3** [comment]
1.0.2已经更新，感谢您的反馈
